[build]
  command = ""          # No build step needed
  publish = "."         # Deploy from the root directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
